### ISSUE TITLE
Setup initial back-end files

### ISSUE THREAD

**Issue by supratikn** [cse442-fall-2019-offering/442projects-loopholes#30]
Create initial files for the back-end which are configured to work with firebase.

**Comment by haanmiba** [comment]
Initial backend is available within the `initialize-backend` branch (https://github.com/cse442-fall-2019-offering/442projects-loopholes/tree/initialize-backend)

The backend sets up a simple REST API and establishes connection with Firebase but have not attempted creating database entry as of yet.

**Comment by haanmiba** [comment]
As of commit [69f3705e](https://github.com/cse442-fall-2019-offering/442projects-loopholes/commit/69f3705e95102c3416c79557ab1799caab3849fd) on branch `initialize-frontend`, the backend API is set up **and** can communicate with our Firebase database.

There exists an endpoint called `/firebaseTestEndpoint` (this will be removed later) where a POST request can be sent with a JSON request body – this JSON request body will be stored in our Firebase Real-Time [database](https://console.firebase.google.com/u/1/project/ubulletin-eb497/database/ubulletin-eb497/data/).

**Comment by haanmiba** [comment]
Onboarding @supratikn to the backend. This required the following steps:

* Install node & npm [[link](https://nodejs.org/en/download/)]
* Create a file `backend/.env` and fill in the Firebase credentials:
```
FIREBASE_API_KEY=SomeFirebaseApiKey
FIREBASE_AUTH_DOMAIN=firebase-auth-domain.firebaseapp.com
FIREBASE_DATABASE_URL=https://firebase-database-url.firebaseio.com
FIREBASE_PROJECT_ID=firebase-project-id
FIREBASE_STORAGE_BUCKET=firebase-storage-bucket.appspot.com
FIREBASE_MESSAGING_SENDER_ID=123456789101
```
* Run the program
```
$ cd backend/
$ npm install   # Installs all dependencies
$ npm build && npm start   # compiles TS to JS and runs Express/Node.js backend
```
* Install Postman [[link](https://www.getpostman.com/)]
* Within Postman, create a `New Request`, set the request type to `POST`, then set `http://localhost:4422/firebaseTestEndpoint` as the address, and the following as the request JSON body:
```
{
	"comments": {},
	"image_link": "https://i.imgur.com/Nqo4swk.jpg",
	"post_id": 2,
	"tags": {
		"art": true
	},
	"timestamp": {
		"day": 22,
		"hour": 21,
		"minute": 21,
		"month": 9,
		"seconds": 4,
		"year": 2019
	},
	"uploader_buffalo_id": "hansbas",
	"uploader_is_anonymous": false,
	"upvotes": {
		"downvoter_buffalo_ids": {
			"hansbas": true
		},
		"num_downvotes": 1,
		"num_upvotes": 1,
		"upvoter_buffalo_ids": {
			"matthewhz": true
		}
	}
}
```
